### ISSUE TITLE
Improve the new CLI UI (multi-progressbar alignments and sizing, etc.)

### ISSUE THREAD

**Issue by imiric** [loadimpact/k6#1279]
This issue tracks some of the CLI UI issues in #1007:

- [x] ~Fix alignment of progress bars to match the longest left text.~ See #1286.
- [x] ~Trim left progress bar text above a certain character threshold.~ See #1286. Still needs to be made configurable.
- [x] ~Display percentages instead of progress bars if window width is smaller than a certain size. Make this format configurable via CLI, so that the user can override it (for CI, etc.).~ See #1332.
- [x] ~Fix some of the text rendering, wording, etc.~ See #1310.
- [ ] Test and fix cross-platform support in as many terminals as possible.

**Comment by na--** [comment]
Sure :smile: the general description of the task would be something like "make the progressbars look and function better in most possible conditions" :sweat_smile: There are a few things that I've noticed could be improved, but I'm probably missing other things, so any ideas and discussion are very welcome. Just keep in mind that, like with a lot of loosely defined tasks, we don't know the precise end state we want to achieve, we just know some of the current issues, so some experimentation and initiative from your side would be necessary...

Let's take the example script from the #1007 description. Run that script in a few different ways:
1. normally, in a full sized terminal window
2. run the script normally, but in a very small terminal window (you might want to comment out the `console.log()` statements for this) - you'd quickly notice a bug...
3. by emulating a CI environment (i.e. a non-TTY stdout and stderr), say `k6 run script.js 2>&1 | cat` or `k6 run --no-color script.js` (this last one works for [complicated](https://github.com/loadimpact/k6/blob/eda42f568cda135300adcf8a25e38ae937ec5899/cmd/ui.go#L124-L126) and [stupid](https://github.com/loadimpact/k6/blob/eda42f568cda135300adcf8a25e38ae937ec5899/cmd/root.go#L79-L91) reasons...)
4. rinse and repeat some of the above steps (or other usage scenarios you can envision) with:
  a. just 1 executor (since that's probably what the majority of k6 users would use, especially first-time users) - from shortcuts (i.e. with the default name) and with long or short name
  b. more or fewer executors
  c. executors with longer or shorter names, or some long and some short names
  d. etc...

I hope you get the idea - try to see how the progress bars look like and function under different conditions - you'd quickly see some issues that need fixing :wink:.

So, if we go with 1. from the list above, you'd see something like this:
```
running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
adjustable_at_will [====>---------------------------------] currently 05 out of 10 active looping VUs, 06.1s/40s
const_loop_vus [==========>---------------------------] constant looping 20 VUs, 06.1s/20s
stages_down_up [==========>---------------------------] currently 08 active looping VUs, 06.1s/20s
stages_up_down [==========>---------------------------] currently 12 active looping VUs, 06.1s/20s
constant_arr_rate [--------------------------------------] waiting 13.9s
variable_arr_rate [--------------------------------------] waiting 13.9s
per_vu_iters [--------------------------------------] waiting 23.9s
shared_iters [--------------------------------------] waiting 23.9s
```

not terrible, especially compared to the earlier versions of that PR (:sweat_smile:), but something like this would be better:
```
running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
adjustable_at_will [====>---------------------------------] currently 05 out of 10 active looping VUs, 06.1s/40s
const_loop_vus     [==========>---------------------------] constant looping 20 VUs, 06.1s/20s
stages_down_up     [==========>---------------------------] currently 08 active looping VUs, 06.1s/20s
stages_up_down     [==========>---------------------------] currently 12 active looping VUs, 06.1s/20s
constant_arr_rate  [--------------------------------------] waiting 13.9s
variable_arr_rate  [--------------------------------------] waiting 13.9s
per_vu_iters       [--------------------------------------] waiting 23.9s
shared_iters       [--------------------------------------] waiting 23.9s
```

As you can imagine, we'll eventually hit some issues with this, especially for longer executor names. So some ideas how we can address that:
1. just noticed that the word `currently` seems superfluous, maybe drop it from [here](https://github.com/loadimpact/k6/blob/eda42f568cda135300adcf8a25e38ae937ec5899/lib/executor/variable_looping_vus.go#L514) to gain some space
2. we should probably trim some long executor names above a certain character threshold like:
    ```
    running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
    super_long_exec... [====>---------------------------------] 05 out of 10 active looping VUs, 06.1s/40s
    const_loop_vus     [==========>---------------------------] constant looping 20 VUs, 06.1s/20s
    stages_down_up     [==========>---------------------------] 08 active looping VUs, 06.1s/20s
    stages_up_down     [==========>---------------------------] 12 active looping VUs, 06.1s/20s
    constant_arr_rate  [--------------------------------------] waiting 13.9s
    variable_arr_rate  [--------------------------------------] waiting 13.9s
    per_vu_iters       [--------------------------------------] waiting 23.9s
    shared_iters       [--------------------------------------] waiting 23.9s
    ```
3. Instead of progress bars, if our terminal window is smaller, maybe we should display percentages? Maybe percentages also look better for non-TTY (i.e. CI) k6 runs? Maybe something like this (not sure if space or zero padded is better, they can probably be better formatted than this example):
   ```
    running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
    super_long_exec... [ 100% ] 05 out of 10 active looping VUs, 06.1s/40s
    const_loop_vus     [  31% ] constant looping 20 VUs, 06.1s/20s
    stages_down_up     [  31% ] 08 active looping VUs, 06.1s/20s
    stages_up_down     [  31% ] 12 active looping VUs, 06.1s/20s
    constant_arr_rate  [   0% ] waiting 13.9s
    variable_arr_rate  [   0% ] waiting 13.9s
    per_vu_iters       [   0% ] waiting 23.9s
    shared_iters       [   0% ] waiting 23.9s
   ```
4. Something else? You get the idea, some iterative experimentation and initiative are definitely required...

For a lot of the things above, you'd need to know the size of the terminal that the user is using, and probably also if/when that changes. I've stumbled upon [this method](https://godoc.org/golang.org/x/crypto/ssh/terminal#GetSize) to do it before, from a library we [already use](https://github.com/loadimpact/k6/blob/7b6b2a684b7f26bbcf1b8549db89614ac398ad54/ui/form_fields.go#L124), but I'm not sure cross-platform it is. Some research is needed, since there might be something better, without going full-blown ncurses. Though some research into things like https://github.com/gdamore/tcell might be a good idea as well...

**Comment by na--** [comment]
btw feel free to improve other semi-connected things while you're at it - be critical to all sorts of things in the UI :wink: Not necessarily in the same PR, now that `new-schedulers` is the new temporary `master`, but feel free to fix (or at least discuss) all sorts of things you think can be improved. For example, I just ran `k6 run --vus 5 --duration 10s github.com/loadimpact/k6/samples/http_get.js` and this was the output:
```
   executor: local
     output: -
     script: github.com/loadimpact/k6/samples/http_get.js

  execution: (100.00%) 1 executors, 5 max VUs, 40s max duration (incl. graceful stop):
           * default: 5 looping VUs for 10s (gracefulStop: 30s)


running (10.2s), 0/5 VUs, 360 complete and 0 interrupted iterations
default [======================================] constant looping 5 VUs for 10s done!
```

Maybe this is wading into bikeshedding territory :sweat_smile:, but:
1. `executor: local` might be a tad confusing, given all of the new "executors", so maybe `execution: local` would be more clear? Or maybe something else? we need to consider that with regard to `k6 cloud` as well, and keep in mind that we'd like to also have native distributed k6 runs soon
2. `1 executors` should probably be `1 executor`
3. I'm wondering if `default` should be the name of the executor we derive from the shortcut execution options... I don't have any better ideas, it just doesn't feel quite right
4. `constant looping 5 VUs for 10s` is awkward, `5 constantly looping VUs for 10s` seems better

**Comment by na--** [comment]
Something else we probably should consider: https://community.k6.io/t/disable-the-test-execution-information-at-console-log/340

Sorry @imiric for constantly expanding the scope of this, but I think we need to look at the new UI/UX in a holistic way, since the progress bars don't exist in isolation.

**Comment by na--** [comment]
Given the better descriptions and information the new progressbars have, for non-TTY outputs, this whole thing might be completely unnecessary: https://github.com/loadimpact/k6/blob/f6be35cfa006c56954d6821e0f94f4863f063e45/cmd/run.go#L308-L323

That said, as I mentioned above, for non-TTY runs, ASCII-art progress bars don't make a lot of sense either, so maybe something like this would be more appropriate to print every second (or maybe even less often?):
```
 running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
 super_long_exec... [ 100% ] 05 out of 10 active looping VUs, 06.1s/40s
 const_loop_vus     [  31% ] constant looping 20 VUs, 06.1s/20s
 stages_down_up     [  31% ] 08 active looping VUs, 06.1s/20s
 stages_up_down     [  31% ] 12 active looping VUs, 06.1s/20s
 constant_arr_rate  [   0% ] waiting 13.9s
 variable_arr_rate  [   0% ] waiting 13.9s
 per_vu_iters       [   0% ] waiting 23.9s
 shared_iters       [   0% ] waiting 23.9s
```

And maybe we don't even need to concern ourselves with any fancy formatting either? 
```
 running (06.1s), 45/50 VUs, 338 complete and 12 interrupted iterations
 super_long_executor_name: 100%, 00 out of 10 active looping VUs, 06.1s/40s
 const_loop_vus: 31%, 20 constantly looping VUs, 06.1s/20s
 ...
 constant_arr_rate: 0%, waiting 13.9s
 ...
```

:man_shrugging: 

btw noticed another minor wording issue: `constant looping 20 VUs` sounds strange, `20 constantly looping VUs` is better

**Comment by imiric** [comment]
The alignment issues were fixed above, and I've been exploring solutions for the text on the right side.

I think the most legible and compact layout would be to standardize the columns and only render the changing values: iterations, VUs, duration, etc. If we use [`text/tabwriter`](https://golang.org/pkg/text/tabwriter/) in `cmd/ui.go` all columns should be neatly aligned and we shouldn't(?) have to think about manual padding and other alignment quirks.

For example:
```sh
               Progress     Iters           VUs   Duration
stages_down_up [ 52%]     123/500         18/50  16.3s/30s
stages_up_down [  4%]         241            25       8.9s
var_arrival... [100%]      153596 (20/s)  14/20        30s
...
```

Note:
- All variable columns would be right-aligned to avoid any "jerkiness" when adding digits.
- Progress for executors for which a maximum value is known would be displayed as `curr/total`, otherwise only the `curr` value would be shown.
- To preserve horizontal space, the executor type would be shown only in the `execution` section during init (along with other details), and the progress section would only reference it with the "friendly" name assigned in the execution options.
- Executors like `variable-arrival-rate` will likely need an additional offset progress column. This can be shown inside round brackets and greyed out, like we currently do for the `data_{received,sent}` metrics.
- Maybe an additional column for "Status" is needed? To show `waiting`/`done`?

Let me know your thoughts on this approach.

**Comment by na--** [comment]
hmm I generally like this proposal, but I have some concerns about its implementation and its flexibility

> standardize the columns and only render the changing values: iterations, VUs, duration, etc

This is my biggest concern - even with the executors we have right now, trying to standardize them presents challenges. Specifically:
- As you've mentioned in the proposal, arrival rate executors have an iters/s metric that would be useful to show.
- Having a separate `Waiting` / `Done` (+ maybe also `Running`?) column would also take space unnecessarily, but I also don't have a better idea :disappointed:. With the current approach, it occupies the same space.
- For performance reasons, we currently don't actually track the iterations attributed to each individual executor, only the total complete/interrupted iterations, and the iterations for the `per-vu-iterations` and `shared-iterations` ones (since we actually need to track those :smile: ).
- If we ever add new executors or improve the current ones, having fixed columns sort of ties our hands a lot in what and how we can present to users.

My implementation concerns are mostly twofold, revolving around performance and complexity:
- `tabwriter` looks cool, but in order to work, it has to keep the whole string output in a buffer and parse and mess with it - even if they've implemented it in a smart way, you can't make that very efficient.
- Also, from what I can see, nothing would prevent the individual columns in the whole "table" from having differing sizes between redraws, which would actually be more annoying than just some numbers on a single row having variable lengths, since it'd shift the whole table... Right-padding isn't enough, when the longest item in a column determines its width, so you'd need both number padding (like we currently have) **and** whatever magic drives the tabwriter algorithm.
- Worse, since we'd have no way to know the line length of whatever table tabwriter produced, we'd probably have to buffer that ourselves and parse it before we show it to the user. That's to prevent the current bug where we don't move the caret enough times upwards when one or more of the lines we output are longer than the terminal size. This would also prevent us from having the "responsive" design of having an actual progressbar if we have space and just displaying `[ xx% ]` when there isn't any. 
- Not to mention that if we *have* to display the status of a single executor on multiple rows, ASCII tables would look worse than the simple text we currently have.

**Comment by imiric** [comment]
Yeah, I agree that standardizing the output into columns would make `ProgressBar` less flexible overall. But then again, I feel like restricting that interface would avoid (ab)using it as a regular line printer, as `hijack()` allows. Plus, a columnar view is much more legible, less text on the screen, etc.

> Having a separate `Waiting` / `Done` (+ maybe also `Running`?) column would also take space unnecessarily, but I also don't have a better idea :(. With the current approach, it occupies the same space.

We could also shorten this respectively to `-` / `✓` and a spinning pipe for progress, immediately following the executor name. I think that would be intuitive enough without having to spell it out. :)

> For performance reasons, we currently don't actually track the iterations attributed to each individual executor, only the total complete/interrupted iterations, and the iterations for the per-vu-iterations and shared-iterations ones

Ah, I wasn't aware of that, and yeah, it's a blocker then if it would impact performance. :(

You're probably right about `tabwriter`. I tested it out briefly and ran into other complications and never got it working, though since there's no way to have fixed size columns, the rendering on redraw could indeed be funky.

So OK, let me fix the smaller leftover things from #1286 and I'll experiment with the right side text some more once I get to the terminal width handling.

**Comment by na--** [comment]
> We could also shorten this respectively to `-` / `✓` and a spinning pipe for progress, immediately following the executor name. I think that would be intuitive enough without having to spell it out. :)

I like this approach! Hopefully doubling down on unicode symbols won't be an issue... https://github.com/loadimpact/k6/issues/1294 :sweat_smile: Though I also think the remaining wait time we currently display after `Waiting ...` could also be useful for users, and won't fit in a single character column :disappointed: 

> Or actually, we could reuse the progress bar itself (the space within square brackets) for this. Show `waiting` centered when displaying the full version, and maybe `[ ... ]` when waiting in the compact output. Running and done states are self-evident because of the progress bar itself (full bar and `100%`), so I don't think we need to handle them separately.

This is more practical, considering how much more space we'd have.

> > For performance reasons, we currently don't actually track the iterations attributed to each individual executor, only the total complete/interrupted iterations, and the iterations for the per-vu-iterations and shared-iterations ones
> 
> Ah, I wasn't aware of that, and yeah, it's a blocker then if it would impact performance. :(

It's probably not a huge deal in terms of performance, just one or two more atomics per executor, but these things start to stack up. It's fine to keep track of executor iterations when you actually need to, but when it's done just so we can fill in a table, I'm starting to get a little bit leery... Also, besides the minor cross-thread contention each atomic adds, we need to keep in mind that if we track the same metric (iterations) in local counters for each executor, and also a total counter for all iterations, for any given snapshot (i.e. rendering of the progress), the sum of the local iteration counters may be different than the global iteration counter (since we'd be updating the atomics separately)...

> So OK, let me fix the smaller leftover things from #1286 and I'll experiment with the right side text some more once I get to the terminal width handling.

:+1:

**Comment by imiric** [comment]
After attempting to take the left side rendering out of the main render loop as discussed in #1286, I ran into several redrawing issues that would need to be worked around, so I don't think exploring that would be worth the complexity. Since the concern is not performance, I think we should abandon that effort.

Also, I looked into some of the libraries we discussed that could be of help:

- https://godoc.org/golang.org/x/crypto/ssh/terminal is not cross-platform (Unix only), though it might be useful for the Unix implementation (`GetSize()`, etc.).

- https://github.com/apoorvam/goterminal: This is quite handy and is cross-platform, but has a few issues, like one measly test and not being maintained, though terminal emulators haven't changed much in the last 40 years (except recently on Windows, maybe... :), and it's a tiny library so we could maintain a fork if needed.

The biggest issue with goterminal is that it requires a small delay between `Print()` and `Clear()` calls, as you can see in the example. When implemented for our `ProgressBar`s this behavior (I think) is responsible for a rather nasty flicker, which makes it unusable as is.

See the video: https://streamable.com/biev8, and the [`feat/1007-1279-goterminal`](https://github.com/imiric/k6/commits/feat/1007-1279-goterminal) branch if you want to test it out. I'm using [st](https://st.suckless.org/) in the video, which has excellent ANSI escape support and great rendering overall, but running it in `urxvt`, a fairly decent and popular terminal, is completely broken (lines are never cleared, and keep appending). So that will need to be fixed as well, and who knows what the behavior will be like on GNOME Terminal or others (Windows...? `darwin` support is missing...).

If the `time.Sleep()` is the issue, I think it could be fixed by passing a callback to `Print()` or via channels or some other mechanism, but that would likely imply maintaining a fork. Since the library is quite useful (`GetTermDimensions()`, etc.) and has a clean API, and we'd likely end up reinventing most of what it's already doing, I vote for forking it and fixing the issues it has.

Let me know what you think.

**Comment by MStoykov** [comment]
https://godoc.org/golang.org/x/crypto/ssh/terminal is not Unix only ... here the [windows implementation](https://github.com/golang/crypto/blob/master/ssh/terminal/util_windows.go) ;)

**Comment by imiric** [comment]
Ah indeed. And goterminal should also support macOS--I misread `writer_posix.go` as `writer_linux.go`. :)

**Comment by imiric** [comment]
So I looked into the flickering issue with goterminal and it can also be reproduced with their own example, just by writing more than a single line of progress, which means it's not related to how we're rendering progress bars.

It seems related to buffering, and Writer uses bytes.Buffer in a couple of places. But strangely enough what solved it was wrapping the passed os.Stdout in a bufio.Writer and calling Flush() on it after writing, which also avoids the need for time.Sleep(). See [the hack](https://github.com/imiric/k6/commit/f54837ad0edcbfdb3cfaf1fccf00213195b94c99). I'm a bit puzzled by this, as all sources I've read mention that stdout is unbuffered in Go, and the previous implementation without goterminal certainly didn't need flushing. What gives?

Anyway, I'll give ssh/terminal another try since it's cross-platform after all, semi-stdlib so surely more stable / tested, and see if we can avoid goterminal. It seems we won't be missing anything if printing is not working well, and `GetTermDimensions` can be replaced with `GetSize`.

**Comment by imiric** [comment]
I implemented some of the ideas discussed here in [feat/1007-1279-compact-text](https://github.com/loadimpact/k6/commits/feat/1007-1279-compact-text). It's built on #1286, so I won't create a PR until that one is merged.

Here's what it looks like so far:
![2020-01-13-145707_1044x303_scrot](https://user-images.githubusercontent.com/1009277/72266771-553a6d80-361f-11ea-8317-4bbe54a1280c.png)

Note the cleanup on the right side, slight alignment and "waiting" being part of the progress bar. I think it's more legible, though the "done!" (or "interrupted!") looks a bit out of place, but I didn't have a better idea for handling it.

Let me know if this is an improvement and/or other ideas to improve it.

**Comment by na--** [comment]
Love the look from the screenshot! And yeah, while cool, waiting can be just a normal status text like it currently is, we're not saving any space by putting in the progress bar. It would have been needed if we had strict columns and had no space for it, but with this semi-free approach we don't need to bother with it.

Also, agree about `done` and `interrupted`, maybe use the unicode green check mark and red X instead?
